@startuml matmat.core.shocks
!pragma useIntermediatePackages false

abstract class matmat.core.base.data.AbstractData {
  _TYPE: str {static}
  _IS_STRUCTURE_VARIABLE: bool {static}
  _NAME: str {static}
  _id: AbstractDataIdentity
  _final_demand_categories: dict
  _idx_builder: IndexBuilder
  _df_rows: pandas.core.indexes.base.Index
  _df_columns: pandas.core.indexes.base.Index
  _df: pandas.core.frame.DataFrame
}
class matmat.core.base.identity.AbstractDataIdentity {
  _regions: dict
  agg_level: str
}
class matmat.core.base.identity.AbstractIdentity {
  _regions: dict
  agg_level: str
  _base_year: int
  _proj_year: int
  scenario_name: str
}
class matmat.core.base.index.core.IndexBuilder {
  _df_index: DataFrame
}

class matmat.core.shocks.extension.builder.ExtensionShockDirector {
  _builder: ExtensionShockBuilder
  id: None
  _extension_categories: list | dict
  _final_demand_categories: dict
}
class matmat.core.shocks.extension.core.ExtensionShock {
  _id: ExtensionShockIdentity 
  _dS_x: SxShockData | NullExtensionShockData 
  _dS_Y: SyShockData | NullExtensionShockData 
  _dS_Z: SzShockData | NullExtensionShockData 
}
class matmat.core.shocks.extension.builder.ExtensionShockBuilder {
  _result: ExtensionShock
}
class matmat.core.shocks.extension.identity.ExtensionShockIdentity {
  extension_name: str
}
class matmat.core.shocks.extension.data.NullExtensionShockData {
}
class matmat.core.shocks.extension.data.SxShockData {
}
class matmat.core.shocks.extension.data.SyShockData {
}
class matmat.core.shocks.extension.data.SzShockData {
}
abstract class matmat.core.shocks.extension.data.AbstractExtensionShockData {
  _id: ExtensionShockDataIdentity 
  _extension_categories: list | dict | None
}
class matmat.core.shocks.extension.identity.ExtensionShockDataIdentity {
  extension_name: str
}
matmat.core.shocks.extension.builder.ExtensionShockDirector *-- matmat.core.shocks.extension.builder.ExtensionShockBuilder
matmat.core.shocks.extension.core.ExtensionShock *-- matmat.core.shocks.extension.identity.ExtensionShockIdentity
matmat.core.shocks.extension.core.ExtensionShock *-- matmat.core.shocks.extension.data.SxShockData
matmat.core.shocks.extension.core.ExtensionShock *-- matmat.core.shocks.extension.data.NullExtensionShockData
matmat.core.shocks.extension.core.ExtensionShock *-- matmat.core.shocks.extension.data.SyShockData
matmat.core.shocks.extension.core.ExtensionShock *-- matmat.core.shocks.extension.data.SzShockData
matmat.core.shocks.extension.builder.ExtensionShockBuilder *-- matmat.core.shocks.extension.core.ExtensionShock
matmat.core.shocks.extension.data.AbstractExtensionShockData *-- matmat.core.shocks.extension.identity.ExtensionShockDataIdentity
matmat.core.shocks.extension.data.AbstractExtensionShockData <|-- matmat.core.shocks.extension.data.NullExtensionShockData
matmat.core.shocks.extension.data.AbstractExtensionShockData <|-- matmat.core.shocks.extension.data.SxShockData
matmat.core.shocks.extension.data.AbstractExtensionShockData <|-- matmat.core.shocks.extension.data.SyShockData
matmat.core.shocks.extension.data.AbstractExtensionShockData <|-- matmat.core.shocks.extension.data.SzShockData
matmat.core.base.identity.AbstractDataIdentity <|-- matmat.core.shocks.extension.identity.ExtensionShockDataIdentity
matmat.core.base.identity.AbstractIdentity <|-- matmat.core.shocks.extension.identity.ExtensionShockIdentity
matmat.core.base.data.AbstractData <|-- matmat.core.shocks.extension.data.AbstractExtensionShockData
matmat.core.base.data.AbstractData *-- matmat.core.base.identity.AbstractDataIdentity
matmat.core.base.data.AbstractData *-- matmat.core.base.index.core.IndexBuilder
footer Generated by //py2puml//
@enduml

