@startuml matmat.core.accounts
!pragma useIntermediatePackages false

abstract class matmat.core.base.data.AbstractData {
  _TYPE: str {static}
  _IS_STRUCTURE_VARIABLE: bool {static}
  _NAME: str {static}
  _id: AbstractDataIdentity
  _final_demand_categories: dict
  _idx_builder: IndexBuilder
  _df_rows: pandas.core.indexes.base.Index
  _df_columns: pandas.core.indexes.base.Index
  _df: pandas.core.frame.DataFrame
}
class matmat.core.base.identity.AbstractDataIdentity {
  _regions: dict
  agg_level: str
}
class matmat.core.base.identity.AbstractIdentity {
  _regions: dict
  agg_level: str
  _base_year: int
  _proj_year: int
  scenario_name: str
}
class matmat.core.base.index.core.IndexBuilder {
  _df_index: DataFrame
}
class matmat.core.accounts.system.core.System {
  _id: SystemIdentity
  _x: XData
  _Y: YData
  _Z: ZData
  _A: AData
  _L: LData
  _Yk: YkData | NullSystemData
  _K: KData | NullSystemData
  _Lk: LkData | NullSystemData
  _unit: UnitSystemData
  _calc_mode: AbstractSrioSystemCalculStrategy
}
class matmat.core.accounts.system.builder.SystemDirector {
  _builder: SystemBuilder
  id: SystemIdentity
  _final_demand_categories: dict
}
class matmat.core.accounts.system.data.AData {
}
class matmat.core.accounts.system.data.KData {
}
class matmat.core.accounts.system.data.LData {
}
class matmat.core.accounts.system.data.LkData {
}
class matmat.core.accounts.system.data.NullSystemData {
}
class matmat.core.accounts.system.data.XData {
}
class matmat.core.accounts.system.data.YData {
}
class matmat.core.accounts.system.data.YkData {
}
class matmat.core.accounts.system.data.ZData {
}
class matmat.core.accounts.system.builder.SystemBuilder {
  _result: System
}
class matmat.core.accounts.system.identity.SystemIdentity {
  strategy: str
}
abstract class matmat.core.accounts.system.strategies.AbstractSrioSystemCalculStrategy {
}
class matmat.core.accounts.system.strategies.Standard {
}
enum matmat.core.accounts.system.strategies.SystemStrategies {
  STANDARD: standard {static}
  EXO_INVEST_MATRIX: exo_invest_matrix {static}
  ENDO_INVEST_MATRIX: endo_invest_matrix {static}
}
class matmat.core.accounts.system.data.UnitSystemData {
}
abstract class matmat.core.accounts.system.data.AbstractSystemData {
  _id: SystemDataIdentity
}
class matmat.core.accounts.system.identity.SystemDataIdentity {
}
class matmat.core.accounts.system.strategies.EndoInvestMatrix {
}
class matmat.core.accounts.system.strategies.ExoInvestMatrix {
}
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.identity.SystemIdentity
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.XData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.YData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.ZData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.AData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.LData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.YkData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.NullSystemData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.KData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.LkData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.data.UnitSystemData
matmat.core.accounts.system.core.System *-- matmat.core.accounts.system.strategies.AbstractSrioSystemCalculStrategy
matmat.core.accounts.system.builder.SystemDirector *-- matmat.core.accounts.system.builder.SystemBuilder
matmat.core.accounts.system.builder.SystemDirector *-- matmat.core.accounts.system.identity.SystemIdentity
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.AData
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.KData
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.LData
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.LkData
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.NullSystemData
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.XData
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.YData
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.YkData
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.ZData
matmat.core.accounts.system.builder.SystemBuilder *-- matmat.core.accounts.system.core.System
matmat.core.accounts.system.strategies.AbstractSrioSystemCalculStrategy <|-- matmat.core.accounts.system.strategies.Standard
matmat.core.accounts.system.data.AbstractSystemData <|-- matmat.core.accounts.system.data.UnitSystemData
matmat.core.accounts.system.data.AbstractSystemData *-- matmat.core.accounts.system.identity.SystemDataIdentity
matmat.core.accounts.system.strategies.Standard <|-- matmat.core.accounts.system.strategies.EndoInvestMatrix
matmat.core.accounts.system.strategies.Standard <|-- matmat.core.accounts.system.strategies.ExoInvestMatrix
matmat.core.base.identity.AbstractDataIdentity <|-- matmat.core.accounts.system.identity.SystemDataIdentity
matmat.core.base.identity.AbstractIdentity <|-- matmat.core.accounts.system.identity.SystemIdentity
matmat.core.base.data.AbstractData <|-- matmat.core.accounts.system.data.AbstractSystemData
matmat.core.base.data.AbstractData *-- matmat.core.base.identity.AbstractDataIdentity
matmat.core.base.data.AbstractData *-- matmat.core.base.index.core.IndexBuilder
footer Generated by //py2puml//
@enduml

