@startuml matmat.core.shocks
!pragma useIntermediatePackages false

abstract class matmat.core.base.data.AbstractData {
  _TYPE: str {static}
  _IS_STRUCTURE_VARIABLE: bool {static}
  _NAME: str {static}
  _id: AbstractDataIdentity
  _final_demand_categories: dict
  _idx_builder: IndexBuilder
  _df_rows: pandas.core.indexes.base.Index
  _df_columns: pandas.core.indexes.base.Index
  _df: pandas.core.frame.DataFrame
}
class matmat.core.base.identity.AbstractDataIdentity {
  _regions: dict
  agg_level: str
}
class matmat.core.base.identity.AbstractIdentity {
  _regions: dict
  agg_level: str
  _base_year: int
  _proj_year: int
  scenario_name: str
}
class matmat.core.base.index.core.IndexBuilder {
  _df_index: DataFrame
}

class matmat.core.shocks.system.core.SystemShock {
  _id: SystemShockIdentity 
  _imp_dom_ratio: ImpDomRatioShockData | NullSystemShockData 
  _dA: AShockData | NullSystemShockData 
  _dK: KShockData | NullSystemShockData 
  _dY: YShockData | NullSystemShockData 
  _dYk: YkShockData | NullSystemShockData 
  _dZ: ZShockData | NullSystemShockData 
}
class matmat.core.shocks.system.builder.SystemShockDirector {
  _builder: SystemShockBuilder
  id: None
  _final_demand_categories: dict
}
class matmat.core.shocks.system.builder.SystemShockBuilder {
  _result: SystemShock
}
class matmat.core.shocks.system.identity.SystemShockIdentity {
}
class matmat.core.shocks.system.data.AShockData {
}
class matmat.core.shocks.system.data.ImpDomRatioShockData {
}
class matmat.core.shocks.system.data.KShockData {
}
class matmat.core.shocks.system.data.NullSystemShockData {
}
class matmat.core.shocks.system.data.YShockData {
}
class matmat.core.shocks.system.data.YkShockData {
}
class matmat.core.shocks.system.data.ZShockData {
}
abstract class matmat.core.shocks.system.data.AbstractSystemShockData {
  _id: SystemShockDataIdentity
}
class matmat.core.shocks.system.identity.SystemShockDataIdentity {
}
matmat.core.shocks.system.core.SystemShock *-- matmat.core.shocks.system.identity.SystemShockIdentity
matmat.core.shocks.system.core.SystemShock *-- matmat.core.shocks.system.data.ImpDomRatioShockData
matmat.core.shocks.system.core.SystemShock *-- matmat.core.shocks.system.data.NullSystemShockData
matmat.core.shocks.system.core.SystemShock *-- matmat.core.shocks.system.data.AShockData
matmat.core.shocks.system.core.SystemShock *-- matmat.core.shocks.system.data.KShockData
matmat.core.shocks.system.core.SystemShock *-- matmat.core.shocks.system.data.YShockData
matmat.core.shocks.system.core.SystemShock *-- matmat.core.shocks.system.data.YkShockData
matmat.core.shocks.system.core.SystemShock *-- matmat.core.shocks.system.data.ZShockData
matmat.core.shocks.system.builder.SystemShockDirector *-- matmat.core.shocks.system.builder.SystemShockBuilder
matmat.core.shocks.system.builder.SystemShockBuilder *-- matmat.core.shocks.system.core.SystemShock
matmat.core.shocks.system.data.AbstractSystemShockData *-- matmat.core.shocks.system.identity.SystemShockDataIdentity
matmat.core.shocks.system.data.AbstractSystemShockData <|-- matmat.core.shocks.system.data.AShockData
matmat.core.shocks.system.data.AbstractSystemShockData <|-- matmat.core.shocks.system.data.ImpDomRatioShockData
matmat.core.shocks.system.data.AbstractSystemShockData <|-- matmat.core.shocks.system.data.KShockData
matmat.core.shocks.system.data.AbstractSystemShockData <|-- matmat.core.shocks.system.data.NullSystemShockData
matmat.core.shocks.system.data.AbstractSystemShockData <|-- matmat.core.shocks.system.data.YShockData
matmat.core.shocks.system.data.AbstractSystemShockData <|-- matmat.core.shocks.system.data.YkShockData
matmat.core.shocks.system.data.AbstractSystemShockData <|-- matmat.core.shocks.system.data.ZShockData
matmat.core.base.identity.AbstractDataIdentity <|-- matmat.core.shocks.system.identity.SystemShockDataIdentity
matmat.core.base.identity.AbstractIdentity <|-- matmat.core.shocks.system.identity.SystemShockIdentity
matmat.core.base.data.AbstractData <|-- matmat.core.shocks.system.data.AbstractSystemShockData
matmat.core.base.data.AbstractData *-- matmat.core.base.identity.AbstractDataIdentity
matmat.core.base.data.AbstractData *-- matmat.core.base.index.core.IndexBuilder
footer Generated by //py2puml//
@enduml

